services:
  go-server:
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    networks:
      - marry_me_kafka

  security-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "brawl,not_on_list,person_fell,injured_kid"
      TEAM: "security"
    networks:
      - marry_me_kafka

  cleanup-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "dirty_table,broken_glass_clean_up"
      TEAM: "cleanup"
    networks:
      - marry_me_kafka

  catering-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "bad_food,music_too_loud,music_too_low,feeling_ill_catering"
      TEAM: "catering"
    networks:
      - marry_me_kafka

  officiant-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "missing_rings,missing_bride,missing_groom"
      TEAM: "officiant"
    networks:
      - marry_me_kafka

  waiters-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "broken_glass_waiters,person_fell_waiters,injured_kid_waiters,feeling_ill_waiters"
      TEAM: "waiters"
    networks:
      - marry_me_kafka

networks:
  marry_me_kafka:
