services:
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      - marry_me_kafka

  kafka:
    image: &kafka-image bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./create-topics.sh:/opt/bitnami/kafka/bin/create-topics.sh
    depends_on:
      - kafka-manager
    networks:
      - marry_me_kafka
    healthcheck:
      test:
        [
          "CMD",
          "kafka-topics.sh",
          "--bootstrap-server=localhost:9092",
          "--list",
        ]
      start_period: 5s
      interval: 5s

  init-kafka:
    image: *kafka-image
    working_dir: /opt/bitnami/kafka/bin
    entrypoint: /bin/bash
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./create-topics.sh:/opt/bitnami/kafka/bin/create-topics.sh
    command: -c "./create-topics.sh"
    networks:
      - marry_me_kafka

  kafka-manager:
    image: kafkamanager/kafka-manager:latest
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./application.conf:/kafka-manager/conf/application.conf
    depends_on:
      - zookeeper
    networks:
      - marry_me_kafka

networks:
  marry_me_kafka:
    driver: bridge
