services:
  cleanup-worker-dirty-table-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "dirty_table-Low"
    networks:
      - marry_me_kafka

  cleanup-worker-dirty-table-medium:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "dirty_table-Medium"
    networks:
      - marry_me_kafka

  cleanup-worker-dirty-table-high:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "dirty_table-High"
    networks:
      - marry_me_kafka

  cleanup-worker-broken-items-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "broken_items-Low"
    networks:
      - marry_me_kafka

  cleanup-worker-broken-items-medium:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "broken_items-Medium"
    networks:
      - marry_me_kafka

  cleanup-worker-broken-items-high:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "broken_items-High"
    networks:
      - marry_me_kafka

  catering-worker-bad-food-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "bad_food-Low"
    networks:
      - marry_me_kafka

  catering-worker-bad-food-medium:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "bad_food-Medium"
    networks:
      - marry_me_kafka

  catering-worker-bad-food-high:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "bad_food-High"
    networks:
      - marry_me_kafka

  catering-worker-music-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "music-Low"
    networks:
      - marry_me_kafka

  catering-worker-music-medium:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "music-Medium"
    networks:
      - marry_me_kafka

  catering-worker-music-high:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "music-High"
    networks:
      - marry_me_kafka

  catering-worker-feeling-ill-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "feeling_ill-Low"
    networks:
      - marry_me_kafka

  catering-worker-feeling-ill-medium:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "feeling_ill-Medium"
    networks:
      - marry_me_kafka

  catering-worker-feeling-ill-high:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "feeling_ill-High"
    networks:
      - marry_me_kafka

  officiant-worker-bride-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "bride-Low"
    networks:
      - marry_me_kafka

  officiant-worker-bride-medium:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "bride-Medium"
    networks:
      - marry_me_kafka

  officiant-worker-bride-high:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "bride-High"
    networks:
      - marry_me_kafka

  officiant-worker-groom-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "groom-Low"
    networks:
      - marry_me_kafka

  officiant-worker-groom-medium:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "groom-Medium"
    networks:
      - marry_me_kafka

  officiant-worker-groom-high:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "groom-High"
    networks:
      - marry_me_kafka

  waiters-worker-broken-items-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "broken_items-Low"
    networks:
      - marry_me_kafka

  waiters-worker-broken-items-medium:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "broken_items-Medium"
    networks:
      - marry_me_kafka

  waiters-worker-broken-items-high:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "broken_items-High"
    networks:
      - marry_me_kafka

  waiters-worker-accident-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "accident-Low"
    networks:
      - marry_me_kafka

  waiters-worker-accident-medium:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "accident-Medium"
    networks:
      - marry_me_kafka

  waiters-worker-accident-high:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "accident-High"
    networks:
      - marry_me_kafka

  waiters-worker-feeling-ill-low:
    build:
      context: ./go-worker
    environment:
      PRIORITY: "feeling_ill-Low"
    networks:
      - marry_me_kafka

networks:
  marry_me_kafka:
