services:
  go-server:
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    networks:
      - marry_me_kafka

  security-consumer:
    build:
      context: ./rust-consumer
    environment:
      KAFKA_BROKER: "kafka:29092"
      KAFKA_TOPICS: "brawl,not_on_list,accident"
      KAFKA_GROUP: "security"
      TEAM_ID: "1"
    networks:
      - marry_me_kafka

  cleanup-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:29092"
      KAFKA_TOPICS: "dirty_table,broken_items"
      TEAM: "cleanup"
      TEAM_ID: "2"
    networks:
      - marry_me_kafka

  catering-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:29092"
      KAFKA_TOPICS: "bad_food,music,feeling_ill"
      TEAM: "catering"
      TEAM_ID: "3"
    networks:
      - marry_me_kafka

  officiant-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:29092"
      KAFKA_TOPICS: "bride,groom"
      TEAM: "officiant"
      TEAM_ID: "4"
    networks:
      - marry_me_kafka

  waiters-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:29092"
      KAFKA_TOPICS: "broken_items,accident,feeling_ill"
      TEAM: "waiters"
      TEAM_ID: "5"
    networks:
      - marry_me_kafka

networks:
  marry_me_kafka:
