services:
  go-server:
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    networks:
      - marry_me_kafka

  security-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "brawl,not-on-list,person-fell,injured-kid"
      TEAM: "security"
    networks:
      - marry_me_kafka

  cleanup-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "dirty-table,broken-glass-clean-up"
      TEAM: "cleanup"
    networks:
      - marry_me_kafka

  catering-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "bad-food,music-too-loud,music-too-low,feeling-ill-catering"
      TEAM: "catering"
    networks:
      - marry_me_kafka

  officiant-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "missing-rings,missing-bride,missing-groom"
      TEAM: "officiant"
    networks:
      - marry_me_kafka

  waiters-consumer:
    build:
      context: ./go-consumer
    environment:
      KAFKA_BROKER: "kafka:9092"
      KAFKA_TOPICS: "broken-glass-waiters,person-fell-waiters,injured-kid-waiters,feeling-ill-waiters"
      TEAM: "waiters"
    networks:
      - marry_me_kafka

networks:
  marry_me_kafka:
