services:
  go-server:
    build:
      context: ./go-server
    ports:
      - "8080:8080"
    networks:
      - marry_me_kafka

  go-consumer:
    build:
      context: ./go-consumer
    networks:
      - marry_me_kafka

networks:
  marry_me_kafka:
