[package]
name = "workers"
version = "0.1.0"
edition = "2021"


[[bin]]
path = "src/main.rs"
name = "workers"

[dependencies]
chrono = "0.4.38"
kafka = "0.10.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.120"
